# pakman tree build file
_@ ?= @

.PHONY: MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR QAIC_DIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR MAKE_D_1_LIBDIR MAKE_D_2_LIBDIR android_Release MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR MAKE_D_6_LIBDIR hexagon_Release_dynamic_toolv81_v65 hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_LIBDIR hexagon_Release_dynamic_toolv72_v55 hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v55 hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv72_v60 android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR android_Debug_aarch64_MAKE_D_2_LIBDIR android_Debug_aarch64 hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv81_v62 hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_LIBDIR hexagon_Release_dynamic_toolv81_v62 UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR UbuntuARM_Debug_aarch64 hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v62 hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv81_v65 hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_LIBDIR hexagon_Release_dynamic_toolv81_v60 android_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR android_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR android_Debug_MAKE_D_2_LIBDIR android_Debug android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR android_ReleaseG_MAKE_D_2_LIBDIR android_ReleaseG UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR UbuntuARM_Release_MAKE_D_2_LIBDIR UbuntuARM_Release hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v65 android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR android_ReleaseG_aarch64_MAKE_D_2_LIBDIR android_ReleaseG_aarch64 hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_LIBDIR hexagon_Release_dynamic_toolv72_v60 android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR android_Release_aarch64_MAKE_D_2_LIBDIR android_Release_aarch64 hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v60 hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv72_v55 UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR UbuntuARM_Release_aarch64 UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR UbuntuARM_ReleaseG hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv81_v60 hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v60 UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR UbuntuARM_Debug_MAKE_D_2_LIBDIR UbuntuARM_Debug UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR UbuntuARM_ReleaseG_aarch64 tree MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean QAIC_DIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean MAKE_D_1_LIBDIR_clean MAKE_D_2_LIBDIR_clean android_Release_clean MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean MAKE_D_6_LIBDIR_clean hexagon_Release_dynamic_toolv81_v65_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean hexagon_Release_dynamic_toolv72_v55_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v60_clean android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean android_Debug_aarch64_MAKE_D_2_LIBDIR_clean android_Debug_aarch64_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v62_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean hexagon_Release_dynamic_toolv81_v62_clean UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_clean UbuntuARM_Debug_aarch64_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v65_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean hexagon_Release_dynamic_toolv81_v60_clean android_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean android_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean android_Debug_MAKE_D_2_LIBDIR_clean android_Debug_clean android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean android_ReleaseG_MAKE_D_2_LIBDIR_clean android_ReleaseG_clean UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean UbuntuARM_Release_MAKE_D_2_LIBDIR_clean UbuntuARM_Release_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_clean android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_clean android_ReleaseG_aarch64_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean hexagon_Release_dynamic_toolv72_v60_clean android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean android_Release_aarch64_MAKE_D_2_LIBDIR_clean android_Release_aarch64_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v55_clean UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_clean UbuntuARM_Release_aarch64_clean UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_clean UbuntuARM_ReleaseG_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v60_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_clean UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean UbuntuARM_Debug_MAKE_D_2_LIBDIR_clean UbuntuARM_Debug_clean UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_clean UbuntuARM_ReleaseG_aarch64_clean tree_clean

tree: android_Release hexagon_Release_dynamic_toolv81_v65 hexagon_Release_dynamic_toolv72_v55 hexagon_ReleaseG_dynamic_toolv72_v55 hexagon_Debug_dynamic_toolv72_v60 android_Debug_aarch64 hexagon_Debug_dynamic_toolv81_v62 hexagon_Release_dynamic_toolv81_v62 UbuntuARM_Debug_aarch64 hexagon_ReleaseG_dynamic_toolv81_v62 hexagon_Debug_dynamic_toolv81_v65 hexagon_Release_dynamic_toolv81_v60 android_Debug android_ReleaseG UbuntuARM_Release hexagon_ReleaseG_dynamic_toolv81_v65 android_ReleaseG_aarch64 hexagon_Release_dynamic_toolv72_v60 android_Release_aarch64 hexagon_ReleaseG_dynamic_toolv81_v60 hexagon_Debug_dynamic_toolv72_v55 UbuntuARM_Release_aarch64 UbuntuARM_ReleaseG hexagon_Debug_dynamic_toolv81_v60 hexagon_ReleaseG_dynamic_toolv72_v60 UbuntuARM_Debug UbuntuARM_ReleaseG_aarch64
	$(call job,,$(MAKE) -f all.mak,making .)

tree_clean: android_Release_clean hexagon_Release_dynamic_toolv81_v65_clean hexagon_Release_dynamic_toolv72_v55_clean hexagon_ReleaseG_dynamic_toolv72_v55_clean hexagon_Debug_dynamic_toolv72_v60_clean android_Debug_aarch64_clean hexagon_Debug_dynamic_toolv81_v62_clean hexagon_Release_dynamic_toolv81_v62_clean UbuntuARM_Debug_aarch64_clean hexagon_ReleaseG_dynamic_toolv81_v62_clean hexagon_Debug_dynamic_toolv81_v65_clean hexagon_Release_dynamic_toolv81_v60_clean android_Debug_clean android_ReleaseG_clean UbuntuARM_Release_clean hexagon_ReleaseG_dynamic_toolv81_v65_clean android_ReleaseG_aarch64_clean hexagon_Release_dynamic_toolv72_v60_clean android_Release_aarch64_clean hexagon_ReleaseG_dynamic_toolv81_v60_clean hexagon_Debug_dynamic_toolv72_v55_clean UbuntuARM_Release_aarch64_clean UbuntuARM_ReleaseG_clean hexagon_Debug_dynamic_toolv81_v60_clean hexagon_ReleaseG_dynamic_toolv72_v60_clean UbuntuARM_Debug_clean UbuntuARM_ReleaseG_aarch64_clean
	$(call job,,$(MAKE) -f all.mak clean,cleaning .)

UbuntuARM_ReleaseG_aarch64: UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=UbuntuARM_ReleaseG_aarch64,making .)

UbuntuARM_ReleaseG_aarch64_clean: UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_clean UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=UbuntuARM_ReleaseG_aarch64 clean,cleaning .)

UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR: UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_ReleaseG_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_clean: UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_ReleaseG_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_ReleaseG_aarch64,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_ReleaseG_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_ReleaseG_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

UbuntuARM_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_ReleaseG_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

UbuntuARM_Debug: UbuntuARM_Debug_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_Debug_MAKE_D_2_LIBDIR UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=UbuntuARM_Debug,making .)

UbuntuARM_Debug_clean: UbuntuARM_Debug_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_Debug_MAKE_D_2_LIBDIR_clean UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=UbuntuARM_Debug clean,cleaning .)

UbuntuARM_Debug_MAKE_D_2_LIBDIR: UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_Debug,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_Debug_MAKE_D_2_LIBDIR_clean: UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_Debug clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_Debug,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_Debug clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_Debug,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

UbuntuARM_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_Debug clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv72_v60: hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60,making .)

hexagon_ReleaseG_dynamic_toolv72_v60_clean: hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60 clean,cleaning .)

hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR: hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean: hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_ReleaseG_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Debug_dynamic_toolv81_v60: hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60,making .)

hexagon_Debug_dynamic_toolv81_v60_clean: hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60 clean,cleaning .)

hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR: hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean: hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Debug_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_ReleaseG: UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=UbuntuARM_ReleaseG,making .)

UbuntuARM_ReleaseG_clean: UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_clean UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=UbuntuARM_ReleaseG clean,cleaning .)

UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR: UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_ReleaseG,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_clean: UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_ReleaseG clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_ReleaseG,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_ReleaseG clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_ReleaseG,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

UbuntuARM_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_ReleaseG clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

UbuntuARM_Release_aarch64: UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=UbuntuARM_Release_aarch64,making .)

UbuntuARM_Release_aarch64_clean: UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_clean UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=UbuntuARM_Release_aarch64 clean,cleaning .)

UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR: UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_Release_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_clean: UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_Release_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_Release_aarch64,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_Release_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_Release_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

UbuntuARM_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_Release_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv72_v55: hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55,making .)

hexagon_Debug_dynamic_toolv72_v55_clean: hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55 clean,cleaning .)

hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR: hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean: hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Debug_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_ReleaseG_dynamic_toolv81_v60: hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60,making .)

hexagon_ReleaseG_dynamic_toolv81_v60_clean: hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60 clean,cleaning .)

hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR: hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean: hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_ReleaseG_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_Release_aarch64: android_Release_aarch64_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_Release_aarch64_MAKE_D_2_LIBDIR android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=android_Release_aarch64,making .)

android_Release_aarch64_clean: android_Release_aarch64_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_Release_aarch64_MAKE_D_2_LIBDIR_clean android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=android_Release_aarch64 clean,cleaning .)

android_Release_aarch64_MAKE_D_2_LIBDIR: android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_Release_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_Release_aarch64_MAKE_D_2_LIBDIR_clean: android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_Release_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_Release_aarch64,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_Release_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_Release_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

android_Release_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_Release_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv72_v60: hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_LIBDIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60,making .)

hexagon_Release_dynamic_toolv72_v60_clean: hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60 clean,cleaning .)

hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR: hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean: hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Release_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_ReleaseG_aarch64: android_ReleaseG_aarch64_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_ReleaseG_aarch64_MAKE_D_2_LIBDIR android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=android_ReleaseG_aarch64,making .)

android_ReleaseG_aarch64_clean: android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_clean android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=android_ReleaseG_aarch64 clean,cleaning .)

android_ReleaseG_aarch64_MAKE_D_2_LIBDIR: android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_ReleaseG_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_clean: android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_ReleaseG_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_ReleaseG_aarch64,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_ReleaseG_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_ReleaseG_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

android_ReleaseG_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_ReleaseG_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv81_v65: hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65,making .)

hexagon_ReleaseG_dynamic_toolv81_v65_clean: hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65 clean,cleaning .)

hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR: hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean: hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_ReleaseG_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Release: UbuntuARM_Release_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_Release_MAKE_D_2_LIBDIR UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=UbuntuARM_Release,making .)

UbuntuARM_Release_clean: UbuntuARM_Release_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_Release_MAKE_D_2_LIBDIR_clean UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=UbuntuARM_Release clean,cleaning .)

UbuntuARM_Release_MAKE_D_2_LIBDIR: UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_Release,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_Release_MAKE_D_2_LIBDIR_clean: UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_Release clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_Release,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_Release clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_Release,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

UbuntuARM_Release_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_Release clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

android_ReleaseG: android_ReleaseG_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_ReleaseG_MAKE_D_2_LIBDIR android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=android_ReleaseG,making .)

android_ReleaseG_clean: android_ReleaseG_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_ReleaseG_MAKE_D_2_LIBDIR_clean android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=android_ReleaseG clean,cleaning .)

android_ReleaseG_MAKE_D_2_LIBDIR: android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_ReleaseG,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_ReleaseG_MAKE_D_2_LIBDIR_clean: android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_ReleaseG clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_ReleaseG,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_ReleaseG clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_ReleaseG,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

android_ReleaseG_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_ReleaseG clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

android_Debug: android_Debug_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_Debug_MAKE_D_2_LIBDIR android_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=android_Debug,making .)

android_Debug_clean: android_Debug_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_Debug_MAKE_D_2_LIBDIR_clean android_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=android_Debug clean,cleaning .)

android_Debug_MAKE_D_2_LIBDIR: android_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_Debug,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_Debug_MAKE_D_2_LIBDIR_clean: android_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_Debug clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_Debug,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_Debug_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_Debug clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_Debug,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

android_Debug_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_Debug clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv81_v60: hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_LIBDIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60,making .)

hexagon_Release_dynamic_toolv81_v60_clean: hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60 clean,cleaning .)

hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR: hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_clean: hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv81_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Release_dynamic_toolv81_v60_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv81_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Debug_dynamic_toolv81_v65: hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65,making .)

hexagon_Debug_dynamic_toolv81_v65_clean: hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65 clean,cleaning .)

hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR: hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean: hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Debug_dynamic_toolv81_v65_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_ReleaseG_dynamic_toolv81_v62: hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62,making .)

hexagon_ReleaseG_dynamic_toolv81_v62_clean: hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62 clean,cleaning .)

hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR: hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean: hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_ReleaseG_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Debug_aarch64: UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=UbuntuARM_Debug_aarch64,making .)

UbuntuARM_Debug_aarch64_clean: UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_clean UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=UbuntuARM_Debug_aarch64 clean,cleaning .)

UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR: UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_Debug_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_clean: UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=UbuntuARM_Debug_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_Debug_aarch64,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=UbuntuARM_Debug_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_Debug_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

UbuntuARM_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=UbuntuARM_Debug_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv81_v62: hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_LIBDIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62,making .)

hexagon_Release_dynamic_toolv81_v62_clean: hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62 clean,cleaning .)

hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR: hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean: hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Release_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Debug_dynamic_toolv81_v62: hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62,making .)

hexagon_Debug_dynamic_toolv81_v62_clean: hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62 clean,cleaning .)

hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR: hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_clean: hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv81_v62_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Debug_dynamic_toolv81_v62_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv81_v62 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_Debug_aarch64: android_Debug_aarch64_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_Debug_aarch64_MAKE_D_2_LIBDIR android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=android_Debug_aarch64,making .)

android_Debug_aarch64_clean: android_Debug_aarch64_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_Debug_aarch64_MAKE_D_2_LIBDIR_clean android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=android_Debug_aarch64 clean,cleaning .)

android_Debug_aarch64_MAKE_D_2_LIBDIR: android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_Debug_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_Debug_aarch64_MAKE_D_2_LIBDIR_clean: android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_Debug_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_Debug_aarch64,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_Debug_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_Debug_aarch64,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

android_Debug_aarch64_MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_Debug_aarch64 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv72_v60: hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_LIBDIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60,making .)

hexagon_Debug_dynamic_toolv72_v60_clean: hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60 clean,cleaning .)

hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR: hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_clean: hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv72_v60_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Debug_dynamic_toolv72_v60_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Debug_dynamic_toolv72_v60 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_ReleaseG_dynamic_toolv72_v55: hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_LIBDIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55,making .)

hexagon_ReleaseG_dynamic_toolv72_v55_clean: hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55 clean,cleaning .)

hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR: hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean: hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_ReleaseG_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_ReleaseG_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Release_dynamic_toolv72_v55: hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_LIBDIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55,making .)

hexagon_Release_dynamic_toolv72_v55_clean: hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55 clean,cleaning .)

hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR: hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_clean: hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv72_v55_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Release_dynamic_toolv72_v55_MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv72_v55 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

hexagon_Release_dynamic_toolv81_v65: MAKE_D_6_INCDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_6_INCDIR hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR MAKE_D_6_LIBDIR MAKE_D_6_LIBDIR
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65,making .)

hexagon_Release_dynamic_toolv81_v65_clean: MAKE_D_6_INCDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_6_INCDIR_clean hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean MAKE_D_6_LIBDIR_clean MAKE_D_6_LIBDIR_clean
	$(call job,,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65 clean,cleaning .)

MAKE_D_6_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/test/common/test_main)

MAKE_D_6_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_main,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_main)

hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR: hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR MAKE_D_6_INCDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_clean: hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean MAKE_D_6_INCDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

hexagon_Release_dynamic_toolv81_v65_MAKE_D_4_INCDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

MAKE_D_6_INCDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

MAKE_D_6_INCDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=hexagon_Release_dynamic_toolv81_v65 clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

android_Release: MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR
	$(call job,,$(MAKE) V=android_Release,making .)

android_Release_clean: MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean
	$(call job,,$(MAKE) V=android_Release clean,cleaning .)

MAKE_D_2_LIBDIR: MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR MAKE_D_1_LIBDIR
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_Release,making $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

MAKE_D_2_LIBDIR_clean: MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean MAKE_D_1_LIBDIR_clean
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/rpcmem,$(MAKE) V=android_Release clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/rpcmem)

MAKE_D_1_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_Release,making $(HEXAGON_SDK_ROOT)/test/common/test_util)

MAKE_D_1_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/test/common/test_util,$(MAKE) V=android_Release clean,cleaning $(HEXAGON_SDK_ROOT)/test/common/test_util)

MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR: QAIC_DIR

MAKE_D_2_LIBDIR_MAKE_D_EXT_4_DIR_clean: QAIC_DIR_clean

QAIC_DIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/tools/qaic,make,making $(HEXAGON_SDK_ROOT)/tools/qaic)

QAIC_DIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/tools/qaic,make clean,cleaning $(HEXAGON_SDK_ROOT)/tools/qaic)

MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_Release,making $(HEXAGON_SDK_ROOT)/libs/common/atomic)

MAKE_D_2_LIBDIR_MAKE_D_2_LIBDIR_clean: 
	$(call job,$(HEXAGON_SDK_ROOT)/libs/common/atomic,$(MAKE) V=android_Release clean,cleaning $(HEXAGON_SDK_ROOT)/libs/common/atomic)

W := $(findstring ECHO,$(shell echo))# W => Windows environment
@LOG = $(if $W,$(TEMP)\\)$@-build.log

C = $(if $1,cd $1 && )$2
job = $(_@)echo $3 && ( $C )> $(@LOG) && $(if $W,del,rm) $(@LOG) || ( echo ERROR $3 && $(if $W,type,cat) $(@LOG) && $(if $W,del,rm) $(@LOG) && exit 1)
ifdef VERBOSE
  job = $(_@)echo $3 && $C
endif
